### ISSUE TITLE
Use Entra ID as the auth model rather than management storage table

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/azure-openai-service-proxy#42]

**Comment by cmaneu** [comment]
I would say that these two should be supported. We're building a workshop experience that relies on custom tokens generated per user. We are directly writing into the storage table for this. 

Because we will have participants from anywhere (without an Entra ID), we can't rely on it. If this capability is removed from the proxy, we will have to either use an older version or rebuild it.

**Comment by aaronpowell** [comment]
> I would say that these two should be supported. We're building a workshop experience that relies on custom tokens generated per user. We are directly writing into the storage table for this.
> 
> Because we will have participants from anywhere (without an Entra ID), we can't rely on it. If this capability is removed from the proxy, we will have to either use an older version or rebuild it.

Entra ID is going to be for the Microsoft sponsor of the event, not the participants of the event. For participants, we'll be sticking with the standard approach of GUIDs for the time being.

**Comment by aaronpowell** [comment]
Closed with #43
